// <auto-generated />
using System;
using System.Collections.Generic;
using ElectronFlowSim.AnalysisService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElectronFlowSim.AnalysisService.GRPC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250806082602_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElectronFlowSim.AnalysisService.Domain.Entities.InputData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SaveDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SaveName")
                        .HasColumnType("text");

                    b.Property<double>("abm")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<double[]>("aik")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double>("akl1")
                        .HasColumnType("double precision");

                    b.Property<double>("ar1s")
                        .HasColumnType("double precision");

                    b.Property<double>("dtok")
                        .HasColumnType("double precision");

                    b.Property<double>("dz")
                        .HasColumnType("double precision");

                    b.Property<double>("hq1")
                        .HasColumnType("double precision");

                    b.Property<double>("ht")
                        .HasColumnType("double precision");

                    b.Property<int>("icr")
                        .HasColumnType("integer");

                    b.Property<int>("ig")
                        .HasColumnType("integer");

                    b.Property<int>("ik")
                        .HasColumnType("integer");

                    b.Property<int>("j1")
                        .HasColumnType("integer");

                    b.Property<int>("jcr")
                        .HasColumnType("integer");

                    b.Property<int>("km")
                        .HasColumnType("integer");

                    b.Property<int>("kp")
                        .HasColumnType("integer");

                    b.Property<int>("kpj6")
                        .HasColumnType("integer");

                    b.Property<int>("kq")
                        .HasColumnType("integer");

                    b.Property<int>("nl")
                        .HasColumnType("integer");

                    b.Property<int>("nmas")
                        .HasColumnType("integer");

                    b.Property<double>("rk")
                        .HasColumnType("double precision");

                    b.Property<double>("u0")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<double[]>("uekvip")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double>("utep")
                        .HasColumnType("double precision");

                    b.Property<double>("zkon")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("InputDatas");
                });

            modelBuilder.Entity("ElectronFlowSim.AnalysisService.Domain.Entities.InputData", b =>
                {
                    b.OwnsOne("ElectronFlowSim.AnalysisService.Domain.Entities.BMTableData", "BMTableData", b1 =>
                        {
                            b1.Property<Guid>("InputDataId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<double>>("Bm")
                                .IsRequired()
                                .HasColumnType("double precision[]");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<double>>("Z")
                                .IsRequired()
                                .HasColumnType("double precision[]");

                            b1.Property<double>("bnorm")
                                .HasColumnType("double precision");

                            b1.HasKey("InputDataId");

                            b1.ToTable("BMTableDatas");

                            b1.WithOwner()
                                .HasForeignKey("InputDataId");
                        });

                    b.OwnsOne("ElectronFlowSim.AnalysisService.Domain.Entities.NLTableData", "NLTableData", b1 =>
                        {
                            b1.Property<Guid>("InputDataId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<int>>("L")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.PrimitiveCollection<List<int>>("N")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.HasKey("InputDataId");

                            b1.ToTable("NLTableDatas");

                            b1.WithOwner()
                                .HasForeignKey("InputDataId");
                        });

                    b.OwnsMany("ElectronFlowSim.AnalysisService.Domain.Entities.NZRUTableData", "NZRUTableDatas", b1 =>
                        {
                            b1.Property<Guid>("InputDataId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<int>>("N")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.PrimitiveCollection<List<double>>("R")
                                .IsRequired()
                                .HasColumnType("double precision[]");

                            b1.Property<double>("U")
                                .HasColumnType("double precision");

                            b1.Property<int>("WorkpieceType")
                                .HasColumnType("integer");

                            b1.PrimitiveCollection<List<double>>("Z")
                                .IsRequired()
                                .HasColumnType("double precision[]");

                            b1.HasKey("InputDataId", "Id");

                            b1.ToTable("NZRUTableDatas");

                            b1.WithOwner()
                                .HasForeignKey("InputDataId");
                        });

                    b.Navigation("BMTableData")
                        .IsRequired();

                    b.Navigation("NLTableData")
                        .IsRequired();

                    b.Navigation("NZRUTableDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
