// <auto-generated />
using System;
using ElectronFlowSim.AnalysisService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElectronFlowSim.AnalysisService.GRPC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250703094542_add_datetime")]
    partial class add_datetime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElectronFlowSim.AnalysisService.Domain.Entities.InputData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SaveDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("abm")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<double[]>("aik")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double>("akl1")
                        .HasColumnType("double precision");

                    b.Property<double>("ar1s")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<double[]>("bm")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double>("bnorm")
                        .HasColumnType("double precision");

                    b.Property<double>("dtok")
                        .HasColumnType("double precision");

                    b.Property<double>("dz")
                        .HasColumnType("double precision");

                    b.Property<double>("hq1")
                        .HasColumnType("double precision");

                    b.Property<double>("ht")
                        .HasColumnType("double precision");

                    b.Property<int>("icr")
                        .HasColumnType("integer");

                    b.Property<int>("ig")
                        .HasColumnType("integer");

                    b.Property<int>("ik")
                        .HasColumnType("integer");

                    b.Property<int>("j1")
                        .HasColumnType("integer");

                    b.Property<int>("jcr")
                        .HasColumnType("integer");

                    b.Property<int>("km")
                        .HasColumnType("integer");

                    b.Property<int>("kp")
                        .HasColumnType("integer");

                    b.Property<int>("kpj6")
                        .HasColumnType("integer");

                    b.Property<int>("kq")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("l")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("nmas")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<double[]>("r")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double>("rk")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<double[]>("u")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double>("u0")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<double[]>("uekvip")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double>("utep")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<double[]>("z")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double>("zkon")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("InputDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
