// <auto-generated />
using System;
using System.Collections.Generic;
using ElectronFlowSim.AnalysisService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElectronFlowSim.AnalysisService.GRPC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElectronFlowSim.AnalysisService.Domain.Entities.InputData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("NLTableDataId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SaveDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SaveName")
                        .HasColumnType("text");

                    b.Property<double>("abm")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<double[]>("aik")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double>("akl1")
                        .HasColumnType("double precision");

                    b.Property<double>("ar1s")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<double[]>("bm")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double>("bnorm")
                        .HasColumnType("double precision");

                    b.Property<double>("dtok")
                        .HasColumnType("double precision");

                    b.Property<double>("dz")
                        .HasColumnType("double precision");

                    b.Property<double>("hq1")
                        .HasColumnType("double precision");

                    b.Property<double>("ht")
                        .HasColumnType("double precision");

                    b.Property<int>("icr")
                        .HasColumnType("integer");

                    b.Property<int>("ig")
                        .HasColumnType("integer");

                    b.Property<int>("ik")
                        .HasColumnType("integer");

                    b.Property<int>("j1")
                        .HasColumnType("integer");

                    b.Property<int>("jcr")
                        .HasColumnType("integer");

                    b.Property<int>("km")
                        .HasColumnType("integer");

                    b.Property<int>("kp")
                        .HasColumnType("integer");

                    b.Property<int>("kpj6")
                        .HasColumnType("integer");

                    b.Property<int>("kq")
                        .HasColumnType("integer");

                    b.Property<int>("nmas")
                        .HasColumnType("integer");

                    b.Property<double>("rk")
                        .HasColumnType("double precision");

                    b.Property<double>("u0")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<double[]>("uekvip")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double>("utep")
                        .HasColumnType("double precision");

                    b.Property<double>("zkon")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("NLTableDataId");

                    b.ToTable("InputDatas");
                });

            modelBuilder.Entity("ElectronFlowSim.AnalysisService.Domain.Entities.NLTableData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<int>>("L")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<List<int>>("N")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.ToTable("NLTableDatas");
                });

            modelBuilder.Entity("ElectronFlowSim.AnalysisService.Domain.Entities.NZRUTableData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<int>>("N")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<List<double>>("R")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double>("U")
                        .HasColumnType("double precision");

                    b.Property<int>("WorkpieceType")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<double>>("Z")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.HasKey("Id");

                    b.ToTable("NZRUTableDatas");
                });

            modelBuilder.Entity("InputDataNZRUTableData", b =>
                {
                    b.Property<Guid>("InputDataId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NZRUTableDatasId")
                        .HasColumnType("uuid");

                    b.HasKey("InputDataId", "NZRUTableDatasId");

                    b.HasIndex("NZRUTableDatasId");

                    b.ToTable("InputDataNZRUTableData");
                });

            modelBuilder.Entity("ElectronFlowSim.AnalysisService.Domain.Entities.InputData", b =>
                {
                    b.HasOne("ElectronFlowSim.AnalysisService.Domain.Entities.NLTableData", "NLTableData")
                        .WithMany()
                        .HasForeignKey("NLTableDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NLTableData");
                });

            modelBuilder.Entity("InputDataNZRUTableData", b =>
                {
                    b.HasOne("ElectronFlowSim.AnalysisService.Domain.Entities.InputData", null)
                        .WithMany()
                        .HasForeignKey("InputDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronFlowSim.AnalysisService.Domain.Entities.NZRUTableData", null)
                        .WithMany()
                        .HasForeignKey("NZRUTableDatasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
